//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalDemo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonalDemoContext : DbContext
    {
        public PersonalDemoContext()
            : base("name=PersonalDemoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectDuty> ProjectDuties { get; set; }
        public virtual DbSet<ProjectTechnique> ProjectTechniques { get; set; }
        public virtual DbSet<SkillSummary> SkillSummaries { get; set; }
        public virtual DbSet<WorkExp> WorkExps { get; set; }
        public virtual DbSet<Referee> Referees { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<PositionDuty> PositionDuties { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
    }
}
