//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referee
    {
        public int RefereeID { get; set; }
        public string Comment { get; set; }
        public string RefereeName { get; set; }
    }
}
